config/routes.rb
Children::Application.routes.draw do
  resources :parents

  resources :children

  resources :families

  devise_for :users

  namespace :admin do
    resources :users
  end

  get "home/index"

  

  root :to => "home#index"
end

app/models/family.rb
class Family < ActiveRecord::Base
	has_many :children
	belongs_to :father, class_name: 'Parent'
	belongs_to :mother, class_name: 'Parent'

	def father_full_name
		self.father.full_name if self.father
	end

	def mother_full_name
		self.mother.full_name if self.mother
	end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_family, only: [:show, :edit, :update, :destroy]

  # GET /families
  # GET /families.json
  def index
    @families = Family.scoped

    query = (params[:q] || '').strip
    if request.xhr?
      unless query.empty?
        @families.where!('name ILIKE ?', "%#{query}%")
      else
        @families = []
      end
      return render json: @families.map {|s| {id: s.id, text: s.name}}
    end
  end

  # GET /families/1
  # GET /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families
  # POST /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: 'Family was successfully created.' }
        format.json { render action: 'show', status: :created, location: @family }
      else
        format.html { render action: 'new' }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1
  # PATCH/PUT /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to @family, notice: 'Family was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_params
      params.require(:family).permit(:name, :address, :phone, :desc, :father_id, :mother_id)
    end
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_form.html.haml
= form_for @family, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
    %br
      %br
      %table
        %tr
          %td
            .control-group
              = f.label :father, :class => 'control-label'
              .controls
                =# f.number_field :father_id, :class => 'text_field'
                = f.hidden_field :father_id, style: 'width: 220px', title: @family.father_full_name, autocompletion_path: parents_path
          %td        
            .control-group
              = f.label :mother, :class => 'control-label'
              .controls
                =# f.number_field :mother_id, :class => 'text_field'
                = f.hidden_field :mother_id, style: 'width: 220px', title: @family.mother_full_name, autocompletion_path: parents_path

  .control-group
    = f.label :address, :class => 'control-label'
    .controls
      = f.text_field :address, :class => 'text_field'
  .control-group
    = f.label :phone, :class => 'control-label'
    .controls
      = f.telephone_field :phone, :class => 'text_field'
  .control-group
    = f.label :desc, :class => 'control-label'
    .controls
      = f.text_area :desc, :class => 'text_field'

    .well
      %table.table.table-bordered
        %caption Список Детей
        %thead
          %tr
            %th Код
            %th Имя
            %th Возраст
            %th Приёмный?
        %tbody
          - @family.children.each do |c|
            %tr
              %td= c.id
              %td= c.full_name
              %td= c.age
              %td= check_box_tag "adopted","1", c.adopted?
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), families_path, :class => 'btn'

app/views/families/edit.html.haml
- model_class = Family
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/families/index.html.haml
- model_class = Family
.page-header
  %h1=t '.title', :default => model_class.model_name.human(count: 2)

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:address)
      %th= model_class.human_attribute_name(:phone)
      
      
      %th.span3=t '.actions', :default => t("helpers.actions")
  %tbody
    - @families.each do |family|
      %tr
        %td= link_to family.id, family_path(family)
        %td= link_to family.name, family_path(family)
        %td= family.address
        %td= family.phone
        
        
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_family_path(family), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), family_path(family), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_family_path, :class => 'btn btn-primary'

app/views/families/new.html.haml
- model_class = Family
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/families/show.html.haml
- model_class = Family
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize
.well
  %p
    %strong= model_class.human_attribute_name(:name) + ':'
  
    = @family.name
    &nbsp&nbsp&nbsp&nbsp
    %strong= model_class.human_attribute_name(:phone) + ':'
    = @family.phone
  %p
    %strong= model_class.human_attribute_name(:father) + ':'
    =@family.father.try :full_name
    &nbsp&nbsp
    %strong= model_class.human_attribute_name(:mother) + ':'
    = @family.mother.try :full_name
  %p
    %strong= model_class.human_attribute_name(:address) + ':'
    = @family.address
  %p
    %strong Детей в семье:
    = @family.children.count
    (в том числе приёмных: #{@family.children.adopted.count})
  %p
    %strong= model_class.human_attribute_name(:desc) + ':'
    = @family.desc
.well
  %table.table.table-bordered
    %caption Список Детей
    %thead
      %tr
        %th Код
        %th Имя
        %th Возраст
        %th Приёмный?
    %tbody
      - @family.children.each do |c|
        %tr
          %td= c.id
          %td= c.full_name
          %td= c.age
          %td= check_box_tag "adopted","1", c.adopted?

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), families_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_family_path(@family), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), family_path(@family), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'