config/routes.rb
Children::Application.routes.draw do
  resources :parents

  resources :children

  resources :families

  devise_for :users

  namespace :admin do
    resources :users
  end

  get "home/index"

  

  root :to => "home#index"
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  belongs_to :family
  validates_inclusion_of :sex, in: %w( m f )
  validates_presence_of :dob, :first_name, :last_name, :doc_number

  def full_name; "#{last_name} #{first_name} #{middle_name}" end
  def family_name
    self.family.name if self.family
  end

  def age
    unless self.dob.nil?
      now = Time.now.utc.to_date
      now.year - self.dob.year - (self.dob.to_date.change(:year => now.year) > now ? 1 : 0)
      end
	end
  
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_parent, only: [:show, :edit, :update, :destroy]

  # GET /parents
  # GET /parents.json
  def index
    @parents = Parent.scoped

    query = (params[:q] || '').strip
    if request.xhr?
      unless query.empty?
        @parents.where!('last_name ILIKE ?', "%#{query}%")
      else
        @parents = []
      end
      return render json: @parents.map {|s| {id: s.id, text: s.full_name}}
    end
  end

  # GET /parents/1
  # GET /parents/1.json
  def show
  end

  # GET /parents/new
  def new
    @parent = Parent.new
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents
  # POST /parents.json
  def create
    @parent = Parent.new(parent_params)

    respond_to do |format|
      if @parent.save
        format.html { redirect_to @parent, notice: 'Parent was successfully created.' }
        format.json { render action: 'show', status: :created, location: @parent }
      else
        format.html { render action: 'new' }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1
  # PATCH/PUT /parents/1.json
  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to @parent, notice: 'Parent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1
  # DELETE /parents/1.json
  def destroy
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_params
      params.require(:parent).permit(:last_name, :middle_name, :first_name, :phone, :sex, :dob, :doc, :doc_number, :desc, :family_id)
    end
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/parents/_form.html.haml
= form_for @parent, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :last_name, :class => 'control-label'
    .controls
      = f.text_field :last_name, :class => 'text_field'
  .control-group
    = f.label :first_name, :class => 'control-label'
    .controls
      = f.text_field :first_name, :class => 'text_field'
  .control-group
    = f.label :middle_name, :class => 'control-label'
    .controls
      = f.text_field :middle_name, :class => 'text_field'
  .control-group
    = f.label :phone, :class => 'control-label'
    .controls
      = f.text_field :phone, :class => 'text_field'
  .control-group
    = f.label :sex, :class => 'control-label'
    .controls
      = f.select :sex, [["Мужской", :m], ["Женский", :f]]
  .control-group
    = f.label :dob, :class => 'control-label'
    .controls
      = f.text_field :dob, "data-behaviour" => "datepicker", "data-date-format" => "yyyy-mm-dd"
  .control-group
    = f.label :doc, :class => 'control-label'
    .controls
      = f.text_field :doc, :class => 'text_field'
  .control-group
    = f.label :doc_number, :class => 'control-label'
    .controls
      = f.text_field :doc_number, :class => 'text_field'
  .control-group
    = f.label :desc, :class => 'control-label'
    .controls
      = f.text_field :desc, :class => 'text_field'
  .control-group
    = f.label :family_id, :class => 'control-label'
    .controls
      = f.hidden_field :family_id, style: 'width: 220px', title: @parent.family_name, autocompletion_path: families_path
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), parents_path, :class => 'btn'

app/views/parents/edit.html.haml
- model_class = Parent
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/parents/index.html.haml
- model_class = Parent
.page-header
  %h1=t '.title', :default => model_class.model_name.human(count: 2)
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:fio)
     
      
      %th= model_class.human_attribute_name(:phone)
      
      %th= model_class.human_attribute_name(:age)
     
      
      %th= model_class.human_attribute_name(:family_id)
      
      %th.span3=t '.actions', :default => t("helpers.actions")
  %tbody
    - @parents.each do |parent|

      %tr
        %td= link_to parent.id, parent_path(parent)
        
        %td=link_to parent.full_name, parent_path(parent)
        
        %td= parent.phone
        
        %td= parent.age
       
        
        %td= parent.family_id
        
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_parent_path(parent), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), parent_path(parent), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_parent_path, :class => 'btn btn-primary'

app/views/parents/new.html.haml
- model_class = Parent
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/parents/show.html.haml
- model_class = Parent
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:fio) + ':'
  
  = @parent.full_name
%p
  %strong= model_class.human_attribute_name(:phone) + ':'
  %br
  = @parent.phone
%p
  %strong= model_class.human_attribute_name(:sex) + ':'
  %br
  = @parent.sex
%p
  %strong= model_class.human_attribute_name(:dob) + ':'
  %br
  = @parent.dob
%p
  %strong= model_class.human_attribute_name(:doc) + ':'
  %br
  = @parent.doc
%p
  %strong= model_class.human_attribute_name(:doc_number) + ':'
  %br
  = @parent.doc_number
%p
  %strong= model_class.human_attribute_name(:desc) + ':'
  %br
  = @parent.desc
%p
  %strong= model_class.human_attribute_name(:family_id) + ':'
  %br
  = @parent.family_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), parents_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_parent_path(@parent), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), parent_path(@parent), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'