config/routes.rb
Children::Application.routes.draw do
  resources :parents

  resources :children

  resources :families

  devise_for :users

  namespace :admin do
    resources :users
  end

  get "home/index"

  

  root :to => "home#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :roles

  def role?(role)
  	return !!self.roles.find_by_name(role.to_s)
  end

  def full_name; "#{last_name} #{first_name} #{middle_name}" end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to [:admin, @user], notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to [:admin, @user], notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :middle_name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.haml
= render partial: '/shared/errors', locals: {obj: @user}

= form_for [:admin, @user], :html => { :class => 'form-horizontal' } do |f|
  
  .control-group
    = f.label :first_name, :class => 'control-label'
    .controls
      = f.text_field :first_name, :class => 'text_field'

  .control-group
    = f.label :last_name, :class => 'control-label'
    .controls
      = f.text_field :last_name, :class => 'text_field'

  .control-group
    = f.label :middle_name, :class => 'control-label'
    .controls
      = f.text_field :middle_name, :class => 'text_field'
      
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  
  .control-group
    = f.label :password, :class => 'control-label'
    .controls
      = f.password_field :password, :class => 'text_field'

  .control-group
    = f.label :password_confirmation, :class => 'control-label'
    .controls
      = f.password_field :password_confirmation, :class => 'text_field'

  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_users_path, :class => 'btn'

app/views/admin/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th №
      %th ФИО
      %th= model_class.human_attribute_name(:email)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, admin_user_path(user)
        %td= user.full_name
        %td= user.email
        %td
          = link_to t('.edit', default: t("helpers.links.edit")), edit_admin_user_path(user), class: 'btn btn-mini'
          = link_to t('.destroy', default: t("helpers.links.destroy")), admin_user_path(user), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Вы уверены?')) }, class: 'btn btn-mini btn-danger'

= link_to t('.new', default: t("helpers.links.new")), new_admin_user_path, class: 'btn btn-primary'

app/views/admin/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:first_name) + ':'
  %br
  = @user.first_name
%p
  %strong= model_class.human_attribute_name(:last_name) + ':'
  %br
  = @user.last_name
%p
  %strong= model_class.human_attribute_name(:middle_name) + ':'
  %br
  = @user.middle_name
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email

%p
  %strong= model_class.human_attribute_name(:last_sign_in_at) + ':'
  %br
  = @user.last_sign_in_at


.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), admin_users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'