config/routes.rb
Children::Application.routes.draw do
  resources :parents

  resources :children

  resources :families

  devise_for :users

  namespace :admin do
    resources :users
  end

  get "home/index"

  

  root :to => "home#index"
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Наши Дети"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"

    = stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true

    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Наши Дети
          .container.nav-collapse
            %ul.nav
              - if user_signed_in?
                - if current_user.role? :admin
                  = nav_item "Пользователи", admin_users_path

            %ul.nav.pull-right
              - if user_signed_in?
                %li.navbar-text= current_user.full_name
                %li= link_to 'Выйти', destroy_user_session_path, method: :delete
              - else
                %li
                  = link_to 'Войти', new_user_session_path

    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Разделы
              = nav_item "Семьи", families_path
              = nav_item "Дети", children_path
              = nav_item "Родители", parents_path
        .span9
          = bootstrap_flash

          = yield
    
      %footer
        %p &copy; Company 2013